version: '3'

services:
  database:
    image: 'mysql/mysql-server:5.7'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=musala
      - MYSQL_USER=musalauser
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init/database/ddl.sql:/docker-entrypoint-initdb.d/1.sql
      - ./init/database/gateways.sql:/docker-entrypoint-initdb.d/2.sql
      - ./init/database/devices.sql:/docker-entrypoint-initdb.d/3.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      timeout: 20s
      retries: 10
    restart: always
    networks:
      - backend
  backend:
    build: .
    ports:
      - "8081"
    links:
      - database
    depends_on:
      - database
    restart: always
    networks:
      - backend
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/musala
      SPRING_DATASOURCE_USERNAME: musalauser
      SPRING_DATASOURCE_PASSWORD: 12345

networks:
  backend:
